[2023-06-20 19:27:27,649] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 318, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-06-20 19:27:27,649] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 318, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 197, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 338, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 318, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-06-20 19:27:27,996] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-06-20 19:27:27,996] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 197, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 338, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-06-20 19:27:28,029] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-06-20 19:27:28,029] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 197, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 338, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-06-20 19:27:28,062] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 318, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-06-20 19:27:28,062] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 318, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 197, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 338, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 318, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-06-20 19:27:28,092] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-06-20 19:27:28,093] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 197, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 338, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-06-20 19:27:28,122] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-06-20 19:27:28,123] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 197, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 338, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-06-20 19:27:28,155] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 318, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-06-20 19:27:28,156] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 318, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 197, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 338, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 318, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-06-20 19:27:28,188] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-06-20 19:27:28,188] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 197, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 338, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-06-20 19:27:28,220] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-06-20 19:27:28,220] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 197, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 338, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-06-20 19:27:28,252] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 318, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-06-20 19:27:28,252] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 318, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 197, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 338, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 318, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-06-20 19:27:28,304] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-06-20 19:27:28,304] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 197, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 338, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-06-20 19:27:28,336] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-06-20 19:27:28,336] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 197, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 338, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-06-20 19:27:28,367] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 318, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-06-20 19:27:28,368] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 318, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 197, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 338, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 318, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-06-20 19:27:28,400] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-06-20 19:27:28,401] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 197, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 338, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-06-20 19:27:28,463] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-06-20 19:27:28,463] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 197, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 338, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


