[2023-08-25 10:43:40,290] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-08-25 10:43:40,291] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 187, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 325, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-08-25 10:43:40,398] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-08-25 10:43:40,398] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 187, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 325, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-08-25 10:43:40,431] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-08-25 10:43:40,431] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 187, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 325, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-08-25 10:43:40,463] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-08-25 10:43:40,463] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 187, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 325, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-08-25 10:43:40,496] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-08-25 10:43:40,496] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 187, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 325, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-08-25 10:43:40,527] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-08-25 10:43:40,528] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 187, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 325, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-08-25 10:43:40,559] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-08-25 10:43:40,559] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 187, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 325, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-08-25 10:43:40,591] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-08-25 10:43:40,591] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 187, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 325, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-08-25 10:43:40,623] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-08-25 10:43:40,623] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 187, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 325, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-08-25 10:43:40,655] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-08-25 10:43:40,655] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 187, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 325, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-08-25 10:43:40,687] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-08-25 10:43:40,688] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 187, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 325, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-08-25 10:43:40,720] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-08-25 10:43:40,720] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 187, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 325, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-08-25 10:43:40,755] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-08-25 10:43:40,756] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 187, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 325, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-08-25 10:43:40,799] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-08-25 10:43:40,800] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 187, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 325, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-08-25 10:43:40,841] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-08-25 10:43:40,841] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 187, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 325, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-08-25 10:43:40,885] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-08-25 10:43:40,885] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 187, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 325, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 302, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 142, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


