[2023-12-19 14:06:50,635] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:50,636] logger_util.py->write_log line:61 [INFO] 接口名称：测试连接互联项
[2023-12-19 14:06:50,636] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-12-19 14:06:50,636] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/test
[2023-12-19 14:06:50,636] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:50,636] logger_util.py->write_log line:61 [INFO] 请求参数：{'id': None, 'name': 'mysql7887', 'connectionType': 1, 'databaseType': 1, 'authenticationType': None, 'server': '127.0.0.1', 'port': '3306', 'database': 'TestDB', 'databasePath': '', 'userName': 'root', 'password': 'syc123', 'changedPassword': True, 'mqttType': None, 'pushType': None, 'timingPeriod': None, 'changingPeriod': None, 'cloudDeviceId': '', 'originalSecret': ''}
[2023-12-19 14:06:50,636] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:50,899] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:06:50,899] logger_util.py->write_log line:61 [INFO] 实际结果：测试连接成功
[2023-12-19 14:06:50,900] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:06:50,900] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:06:50,918] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:50,918] logger_util.py->write_log line:61 [INFO] 接口名称：创建互联项
[2023-12-19 14:06:50,918] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-12-19 14:06:50,918] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection
[2023-12-19 14:06:50,918] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:50,918] logger_util.py->write_log line:61 [INFO] 请求参数：{'id': None, 'name': 'mysql3546', 'connectionType': 1, 'databaseType': 1, 'authenticationType': None, 'server': '127.0.0.1', 'port': '3306', 'database': 'TestDB', 'databasePath': '', 'userName': 'root', 'password': 'syc123', 'changedPassword': True, 'mqttType': None, 'pushType': None, 'timingPeriod': None, 'changingPeriod': None, 'cloudDeviceId': '', 'originalSecret': ''}
[2023-12-19 14:06:50,918] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:51,023] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:06:51,023] logger_util.py->write_log line:61 [INFO] 实际结果：{'data': {'id': 1, 'name': 'mysql3546', 'connectionType': 1, 'databaseType': 1, 'authenticationType': 0, 'server': '127.0.0.1', 'port': 3306, 'database': 'TestDB', 'databasePath': '', 'userName': 'root'}, 'message': ''}
[2023-12-19 14:06:51,023] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:06:51,024] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:06:51,034] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:51,034] logger_util.py->write_log line:61 [INFO] 接口名称：关闭互联项
[2023-12-19 14:06:51,035] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-12-19 14:06:51,035] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/switch/1/1/off
[2023-12-19 14:06:51,035] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:51,035] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:51,092] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:06:51,093] logger_util.py->write_log line:61 [INFO] 实际结果：[{'nodeGuid': '6a6a7649-a798-4c90-a71d-3fbcf773eec4', 'id': 1, 'type': 1, 'name': 'mysql3546', 'status': 0, 'errorMsg': None, 'children': []}]
[2023-12-19 14:06:51,093] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:06:51,093] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:06:51,101] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:51,101] logger_util.py->write_log line:61 [INFO] 接口名称：开启互联项
[2023-12-19 14:06:51,102] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-12-19 14:06:51,102] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/switch/1/1/on
[2023-12-19 14:06:51,102] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:51,102] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:51,113] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:06:51,113] logger_util.py->write_log line:61 [INFO] 实际结果：[{'nodeGuid': '4e07e9b4-c1dc-40d2-92e0-0ee6b4ad6e1e', 'id': 1, 'type': 1, 'name': 'mysql3546', 'status': 0, 'errorMsg': None, 'children': []}]
[2023-12-19 14:06:51,114] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:06:51,114] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:06:51,122] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:51,122] logger_util.py->write_log line:61 [INFO] 接口名称：重命名互联项
[2023-12-19 14:06:51,122] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-12-19 14:06:51,122] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/rename/1/1/重命名_mysql125
[2023-12-19 14:06:51,122] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:51,123] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:51,155] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:06:51,155] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-12-19 14:06:51,155] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:06:51,155] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:06:51,182] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:51,182] logger_util.py->write_log line:61 [INFO] 接口名称：修改互联配置
[2023-12-19 14:06:51,182] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-12-19 14:06:51,182] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/1/config
[2023-12-19 14:06:51,182] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:51,182] logger_util.py->write_log line:61 [INFO] 请求参数：{'id': 1, 'name': '改配_mysql530', 'connectionType': 1, 'databaseType': 1, 'authenticationType': 0, 'server': '127.0.0.1', 'port': '3306', 'database': 'TestDB', 'databasePath': '', 'userName': 'root', 'password': 'syc123'}
[2023-12-19 14:06:51,182] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:51,222] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:06:51,222] logger_util.py->write_log line:61 [INFO] 实际结果：{'data': {'id': 1, 'name': '改配_mysql530', 'connectionType': 1, 'databaseType': 1, 'authenticationType': 0, 'server': '127.0.0.1', 'port': 3306, 'database': 'TestDB', 'databasePath': '', 'userName': 'root'}, 'message': ''}
[2023-12-19 14:06:51,223] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:06:51,223] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:06:51,232] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:51,233] logger_util.py->write_log line:61 [INFO] 接口名称：删除互联项
[2023-12-19 14:06:51,233] logger_util.py->write_log line:61 [INFO] 接口方式：delete
[2023-12-19 14:06:51,233] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/1/1
[2023-12-19 14:06:51,233] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:51,233] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:51,269] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:06:51,269] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-12-19 14:06:51,270] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:06:51,270] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:06:51,291] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:51,291] logger_util.py->write_log line:61 [INFO] 接口名称：创建互联项
[2023-12-19 14:06:51,291] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-12-19 14:06:51,291] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection
[2023-12-19 14:06:51,292] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:51,292] logger_util.py->write_log line:61 [INFO] 请求参数：{'id': None, 'name': 'mysql2402', 'connectionType': 1, 'databaseType': 1, 'authenticationType': None, 'server': '127.0.0.1', 'port': '3306', 'database': 'TestDB', 'databasePath': '', 'userName': 'root', 'password': 'syc123', 'changedPassword': True, 'mqttType': None, 'pushType': None, 'timingPeriod': None, 'changingPeriod': None, 'cloudDeviceId': '', 'originalSecret': ''}
[2023-12-19 14:06:51,292] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:51,316] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:06:51,317] logger_util.py->write_log line:61 [INFO] 实际结果：{'data': {'id': 2, 'name': 'mysql2402', 'connectionType': 1, 'databaseType': 1, 'authenticationType': 0, 'server': '127.0.0.1', 'port': 3306, 'database': 'TestDB', 'databasePath': '', 'userName': 'root'}, 'message': ''}
[2023-12-19 14:06:51,317] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:06:51,317] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:06:51,330] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:51,330] logger_util.py->write_log line:61 [INFO] 接口名称：创建映射表
[2023-12-19 14:06:51,330] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-12-19 14:06:51,330] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/2/table
[2023-12-19 14:06:51,330] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:51,330] logger_util.py->write_log line:61 [INFO] 请求参数：{'isBasic': True, 'databaseTableName': 'student', 'querySql': '', 'name': '插入4714'}
[2023-12-19 14:06:51,331] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:51,552] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:06:51,552] logger_util.py->write_log line:61 [INFO] 实际结果：{'id': 1, 'name': '插入4714', 'connectionItemId': 2, 'fields': [{'tableName': 'student', 'tableAlias': '', 'columnName': 'id', 'displayName': 'id', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'time', 'displayName': 'time', 'dataTypeName': 'DateTime', 'databaseTypeName': 'DateTime', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'name', 'displayName': 'name', 'dataTypeName': 'String', 'databaseTypeName': 'VarChar', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'age', 'displayName': 'age', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'money', 'displayName': 'money', 'dataTypeName': 'Single', 'databaseTypeName': 'Float', 'isValueType': True, 'isAsterisk': True}], 'isBasic': True, 'basicDatabaseTableName': 'student', 'querySql': 'select * from `student`', 'detail': None, 'action': None, 'status': 1, 'prevStatus': 0, 'lastErrorMsg': None, 'lastErrorDateTime': None}
[2023-12-19 14:06:51,552] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:06:51,552] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:06:51,566] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:51,566] logger_util.py->write_log line:61 [INFO] 接口名称：关闭映射表
[2023-12-19 14:06:51,567] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-12-19 14:06:51,567] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/switch/2/1/off
[2023-12-19 14:06:51,567] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:51,567] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:51,601] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:06:51,601] logger_util.py->write_log line:61 [INFO] 实际结果：[{'nodeGuid': '46540f0b-4b49-4259-be99-7523d6fdab4b', 'id': 1, 'type': 2, 'name': '插入4714', 'status': 2, 'errorMsg': None, 'children': []}]
[2023-12-19 14:06:51,602] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:06:51,602] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:06:51,611] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:51,611] logger_util.py->write_log line:61 [INFO] 接口名称：开启映射表
[2023-12-19 14:06:51,611] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-12-19 14:06:51,611] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/switch/2/1/on
[2023-12-19 14:06:51,611] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:51,611] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:51,632] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:06:51,632] logger_util.py->write_log line:61 [INFO] 实际结果：[{'nodeGuid': '59b8eaa4-3d46-438a-a440-61b146907b9b', 'id': 1, 'type': 2, 'name': '插入4714', 'status': 1, 'errorMsg': None, 'children': []}]
[2023-12-19 14:06:51,632] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:06:51,632] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:06:51,640] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:51,640] logger_util.py->write_log line:61 [INFO] 接口名称：重命名映射表
[2023-12-19 14:06:51,640] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-12-19 14:06:51,640] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/rename/2/1/student_插入76
[2023-12-19 14:06:51,640] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:51,640] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:51,665] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:06:51,665] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-12-19 14:06:51,666] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:06:51,666] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:06:51,673] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:51,673] logger_util.py->write_log line:61 [INFO] 接口名称：获取映射表配置
[2023-12-19 14:06:51,674] logger_util.py->write_log line:61 [INFO] 接口方式：get
[2023-12-19 14:06:51,674] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/1/config
[2023-12-19 14:06:51,674] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:51,674] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:51,715] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:06:51,715] logger_util.py->write_log line:61 [INFO] 实际结果：{'isBasic': True, 'databaseTableNames': ['student'], 'databaseTableFieldNames': ['id', 'time', 'name', 'age', 'money'], 'querySql': 'select * from `student`'}
[2023-12-19 14:06:51,715] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:06:51,715] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:06:51,722] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:51,723] logger_util.py->write_log line:61 [INFO] 接口名称：映射表创建副本
[2023-12-19 14:06:51,723] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-12-19 14:06:51,723] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/1/copy
[2023-12-19 14:06:51,723] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:51,723] logger_util.py->write_log line:61 [INFO] 请求参数：{'name': '副本61'}
[2023-12-19 14:06:51,723] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:51,758] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:06:51,758] logger_util.py->write_log line:61 [INFO] 实际结果：{'id': 2, 'name': '副本61', 'connectionItemId': 2, 'fields': [{'tableName': 'student', 'tableAlias': '', 'columnName': 'id', 'displayName': 'id', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'time', 'displayName': 'time', 'dataTypeName': 'DateTime', 'databaseTypeName': 'DateTime', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'name', 'displayName': 'name', 'dataTypeName': 'String', 'databaseTypeName': 'VarChar', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'age', 'displayName': 'age', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'money', 'displayName': 'money', 'dataTypeName': 'Single', 'databaseTypeName': 'Float', 'isValueType': True, 'isAsterisk': True}], 'isBasic': True, 'basicDatabaseTableName': 'student', 'querySql': 'select * from `student`', 'detail': None, 'action': None, 'status': 1, 'prevStatus': 0, 'lastErrorMsg': None, 'lastErrorDateTime': None}
[2023-12-19 14:06:51,758] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:06:51,758] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:06:51,771] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:51,771] logger_util.py->write_log line:61 [INFO] 接口名称：删除映射表
[2023-12-19 14:06:51,771] logger_util.py->write_log line:61 [INFO] 接口方式：delete
[2023-12-19 14:06:51,771] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/2/2
[2023-12-19 14:06:51,771] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:51,771] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:51,796] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:06:51,796] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-12-19 14:06:51,797] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:06:51,797] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:06:51,805] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:51,806] logger_util.py->write_log line:61 [INFO] 接口名称：预览数据表
[2023-12-19 14:06:51,806] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-12-19 14:06:51,806] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/2/preview
[2023-12-19 14:06:51,806] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:51,806] logger_util.py->write_log line:61 [INFO] 请求参数：{'isBasic': True, 'databaseTableName': 'student', 'querySql': '', 'limited': 10}
[2023-12-19 14:06:51,806] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:51,849] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:06:51,849] logger_util.py->write_log line:61 [INFO] 实际结果：{'headers': ['id', 'time', 'name', 'age', 'money'], 'data': []}
[2023-12-19 14:06:51,849] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:06:51,849] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:06:51,859] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:51,860] logger_util.py->write_log line:61 [INFO] 接口名称：保存配置-插入
[2023-12-19 14:06:51,860] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-12-19 14:06:51,860] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/1/save
[2023-12-19 14:06:51,860] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:51,860] logger_util.py->write_log line:61 [INFO] 请求参数：{'actionType': 2, 'filters': [], 'sorts': [{'field': 'id', 'sortType': 2}], 'mappings': [{'field': 'time', 'relativeVariable': 'aa16', 'dataType': '日期时间', 'order': 1}, {'field': 'name', 'relativeVariable': 'A12', 'dataType': '字符串', 'order': 2}, {'field': 'age', 'relativeVariable': 'A2', 'dataType': '有符号8位整型', 'order': 3}, {'field': 'money', 'relativeVariable': 'A10', 'dataType': 'F32位浮点数IEEE754', 'order': 4}]}
[2023-12-19 14:06:51,860] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:51,938] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:06:51,938] logger_util.py->write_log line:61 [INFO] 实际结果：{'id': 1, 'name': 'student_插入76', 'connectionItemId': 2, 'fields': [{'tableName': 'student', 'tableAlias': '', 'columnName': 'id', 'displayName': 'id', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'time', 'displayName': 'time', 'dataTypeName': 'DateTime', 'databaseTypeName': 'DateTime', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'name', 'displayName': 'name', 'dataTypeName': 'String', 'databaseTypeName': 'VarChar', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'age', 'displayName': 'age', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'money', 'displayName': 'money', 'dataTypeName': 'Single', 'databaseTypeName': 'Float', 'isValueType': True, 'isAsterisk': True}], 'isBasic': True, 'basicDatabaseTableName': 'student', 'querySql': 'select * from `student`', 'detail': {'actionType': 2, 'filters': [], 'sorts': [{'displayName': 'id', 'sortType': 2}], 'mapping': {'pendingDisplayNameRelativeVariable': None, 'ioMappings': [{'displayName': 'name', 'relativeVariable': 'A12', 'dataType': 16384, 'order': 2}, {'displayName': 'age', 'relativeVariable': 'A2', 'dataType': 2, 'order': 3}, {'displayName': 'money', 'relativeVariable': 'A10', 'dataType': 512, 'order': 4}], 'innerMappings': [{'displayName': 'time', 'relativeVariable': 'aa16', 'dataType': 8192, 'order': 1}], 'systemMappings': []}}, 'action': {'actionType': 2, 'mainSql': 'insert into `student` (`name`,`age`,`money`,`time`) values ({0},{1},{2},{3})', 'sortSql': '`id` desc', 'filterSql': '', 'mainSqlParams': [{'key': 'A12', 'value': False}, {'key': 'A2', 'value': True}, {'key': 'A10', 'value': True}, {'key': 'aa16', 'value': False}], 'filterSqlParams': [], 'assignment': None}, 'status': 1, 'prevStatus': 2, 'lastErrorMsg': None, 'lastErrorDateTime': None}
[2023-12-19 14:06:51,938] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:06:51,939] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:06:51,948] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:51,948] logger_util.py->write_log line:61 [INFO] 接口名称：下发A2=10
[2023-12-19 14:06:51,948] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-12-19 14:06:51,948] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/setvalues
[2023-12-19 14:06:51,949] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981', 'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiU3VwZXJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiU3VwZXJBZG1pbiIsImV4cCI6MTcwMjk0OTM5MiwiaXNzIjoiQ01TdjIiLCJhdWQiOiJBcGkifQ.DTE3ExRd5e35qx7qyEGhaNLjjzP8QxhHUoLCzYg7Hcc'}
[2023-12-19 14:06:51,949] logger_util.py->write_log line:61 [INFO] 请求参数：{'A2': '10'}
[2023-12-19 14:06:51,949] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:51,958] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-12-19 14:06:51,958] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-12-19 14:06:51,958] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-12-19 14:06:51,958] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-12-19 14:06:51,959] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-12-19 14:06:51,959] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 265, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-12-19 14:06:52,074] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:52,074] logger_util.py->write_log line:61 [INFO] 接口名称：下发A10=10.456
[2023-12-19 14:06:52,074] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-12-19 14:06:52,074] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/setvalues
[2023-12-19 14:06:52,075] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981', 'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiU3VwZXJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiU3VwZXJBZG1pbiIsImV4cCI6MTcwMjk0OTM5MiwiaXNzIjoiQ01TdjIiLCJhdWQiOiJBcGkifQ.DTE3ExRd5e35qx7qyEGhaNLjjzP8QxhHUoLCzYg7Hcc'}
[2023-12-19 14:06:52,075] logger_util.py->write_log line:61 [INFO] 请求参数：{'A10': '10.456'}
[2023-12-19 14:06:52,075] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:52,077] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-12-19 14:06:52,077] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-12-19 14:06:52,077] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-12-19 14:06:52,078] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-12-19 14:06:52,078] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-12-19 14:06:52,078] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 265, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-12-19 14:06:52,122] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:52,122] logger_util.py->write_log line:61 [INFO] 接口名称：下发A12=中文1
[2023-12-19 14:06:52,122] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-12-19 14:06:52,122] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/setvalues
[2023-12-19 14:06:52,122] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981', 'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiU3VwZXJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiU3VwZXJBZG1pbiIsImV4cCI6MTcwMjk0OTM5MiwiaXNzIjoiQ01TdjIiLCJhdWQiOiJBcGkifQ.DTE3ExRd5e35qx7qyEGhaNLjjzP8QxhHUoLCzYg7Hcc'}
[2023-12-19 14:06:52,122] logger_util.py->write_log line:61 [INFO] 请求参数：{'A12': '中文1'}
[2023-12-19 14:06:52,123] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:52,125] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-12-19 14:06:52,125] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-12-19 14:06:52,125] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-12-19 14:06:52,125] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-12-19 14:06:52,126] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-12-19 14:06:52,126] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 265, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-12-19 14:06:52,170] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:52,170] logger_util.py->write_log line:61 [INFO] 接口名称：下发aa16=2023-10-20 18:40:55
[2023-12-19 14:06:52,170] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-12-19 14:06:52,170] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/setvalues
[2023-12-19 14:06:52,170] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981', 'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiU3VwZXJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiU3VwZXJBZG1pbiIsImV4cCI6MTcwMjk0OTM5MiwiaXNzIjoiQ01TdjIiLCJhdWQiOiJBcGkifQ.DTE3ExRd5e35qx7qyEGhaNLjjzP8QxhHUoLCzYg7Hcc'}
[2023-12-19 14:06:52,170] logger_util.py->write_log line:61 [INFO] 请求参数：{'aa16': '2023-10-20 18:40:55'}
[2023-12-19 14:06:52,170] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:52,172] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-12-19 14:06:52,173] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-12-19 14:06:52,173] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-12-19 14:06:52,173] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-12-19 14:06:52,173] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-12-19 14:06:52,173] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 265, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-12-19 14:06:52,323] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:52,324] logger_util.py->write_log line:61 [INFO] 接口名称：执行插入语句
[2023-12-19 14:06:52,324] logger_util.py->write_log line:61 [INFO] 接口方式：get
[2023-12-19 14:06:52,324] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/1/executetest
[2023-12-19 14:06:52,324] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:52,324] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:52,877] logger_util.py->error_log line:65 [INFO] 断言失败:A12不等于中文1
[2023-12-19 14:06:52,877] logger_util.py->write_log line:61 [INFO] 实际结果：{'record': {'dateTime': '2023/12/19 14:06:52', 'action': '插入', 'status': '成功', 'data': {'A12': '', 'A2': '', 'A10': '', 'aa16': ''}}, 'info': '测试时间: 2023/12/19 14:06:52\r\n动作: 插入\r\n\r\n数据库:\r\n执行结果: OK\r\n插入时间: 0.01s\r\n', 'status': 1, 'lastErrorMsg': None}
[2023-12-19 14:06:52,877] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-12-19 14:06:52,878] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-12-19 14:06:52,878] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 381, in validate_result
    error_log("断言失败:" + assert_key + "不等于" + str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:A12不等于中文1

[2023-12-19 14:06:52,878] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 381, in validate_result
    error_log("断言失败:" + assert_key + "不等于" + str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:A12不等于中文1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 248, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 381, in validate_result
    error_log("断言失败:" + assert_key + "不等于" + str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:A12不等于中文1


[2023-12-19 14:06:52,918] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:52,918] logger_util.py->write_log line:61 [INFO] 接口名称：刷新-插入
[2023-12-19 14:06:52,918] logger_util.py->write_log line:61 [INFO] 接口方式：get
[2023-12-19 14:06:52,918] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/1/preview
[2023-12-19 14:06:52,919] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:52,919] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:52,943] logger_util.py->error_log line:65 [INFO] 断言失败:age不等于10
[2023-12-19 14:06:52,944] logger_util.py->write_log line:61 [INFO] 实际结果：{'status': 1, 'lastErrorMsg': None, 'total': 1, 'headers': ['id', 'time', 'name', 'age', 'money'], 'data': [{'id': 1, 'time': None, 'name': None, 'age': None, 'money': None}]}
[2023-12-19 14:06:52,944] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-12-19 14:06:52,944] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-12-19 14:06:52,944] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 381, in validate_result
    error_log("断言失败:" + assert_key + "不等于" + str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:age不等于10

[2023-12-19 14:06:52,944] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 381, in validate_result
    error_log("断言失败:" + assert_key + "不等于" + str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:age不等于10

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 248, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 381, in validate_result
    error_log("断言失败:" + assert_key + "不等于" + str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:age不等于10


[2023-12-19 14:06:52,983] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:52,983] logger_util.py->write_log line:61 [INFO] 接口名称：创建映射表-查询
[2023-12-19 14:06:52,983] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-12-19 14:06:52,983] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/2/table
[2023-12-19 14:06:52,983] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:52,983] logger_util.py->write_log line:61 [INFO] 请求参数：{'isBasic': True, 'databaseTableName': 'student', 'querySql': '', 'name': 'student_3562'}
[2023-12-19 14:06:52,983] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:53,008] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:06:53,008] logger_util.py->write_log line:61 [INFO] 实际结果：{'id': 3, 'name': 'student_3562', 'connectionItemId': 2, 'fields': [{'tableName': 'student', 'tableAlias': '', 'columnName': 'id', 'displayName': 'id', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'time', 'displayName': 'time', 'dataTypeName': 'DateTime', 'databaseTypeName': 'DateTime', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'name', 'displayName': 'name', 'dataTypeName': 'String', 'databaseTypeName': 'VarChar', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'age', 'displayName': 'age', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'money', 'displayName': 'money', 'dataTypeName': 'Single', 'databaseTypeName': 'Float', 'isValueType': True, 'isAsterisk': True}], 'isBasic': True, 'basicDatabaseTableName': 'student', 'querySql': 'select * from `student`', 'detail': None, 'action': None, 'status': 1, 'prevStatus': 0, 'lastErrorMsg': None, 'lastErrorDateTime': None}
[2023-12-19 14:06:53,009] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:06:53,009] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:06:54,034] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:54,035] logger_util.py->write_log line:61 [INFO] 接口名称：保存配置-查询
[2023-12-19 14:06:54,035] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-12-19 14:06:54,035] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/3/save
[2023-12-19 14:06:54,035] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:54,035] logger_util.py->write_log line:61 [INFO] 请求参数：{'actionType': 1, 'filters': [], 'sorts': [{'field': 'id', 'sortType': 2}], 'mappings': [{'field': 'time', 'relativeVariable': 'aa16', 'dataType': '日期时间', 'order': 1}, {'field': 'name', 'relativeVariable': 'A12', 'dataType': '字符串', 'order': 2}, {'field': 'age', 'relativeVariable': 'A2', 'dataType': '有符号8位整型', 'order': 3}, {'field': 'money', 'relativeVariable': 'A10', 'dataType': 'F32位浮点数IEEE754', 'order': 4}]}
[2023-12-19 14:06:54,035] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:54,067] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:06:54,067] logger_util.py->write_log line:61 [INFO] 实际结果：{'id': 3, 'name': 'student_3562', 'connectionItemId': 2, 'fields': [{'tableName': 'student', 'tableAlias': '', 'columnName': 'id', 'displayName': 'id', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'time', 'displayName': 'time', 'dataTypeName': 'DateTime', 'databaseTypeName': 'DateTime', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'name', 'displayName': 'name', 'dataTypeName': 'String', 'databaseTypeName': 'VarChar', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'age', 'displayName': 'age', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'money', 'displayName': 'money', 'dataTypeName': 'Single', 'databaseTypeName': 'Float', 'isValueType': True, 'isAsterisk': True}], 'isBasic': True, 'basicDatabaseTableName': 'student', 'querySql': 'select * from `student`', 'detail': {'actionType': 1, 'filters': [], 'sorts': [{'displayName': 'id', 'sortType': 2}], 'mapping': {'pendingDisplayNameRelativeVariable': None, 'ioMappings': [{'displayName': 'name', 'relativeVariable': 'A12', 'dataType': 16384, 'order': 2}, {'displayName': 'age', 'relativeVariable': 'A2', 'dataType': 2, 'order': 3}, {'displayName': 'money', 'relativeVariable': 'A10', 'dataType': 512, 'order': 4}], 'innerMappings': [{'displayName': 'time', 'relativeVariable': 'aa16', 'dataType': 8192, 'order': 1}], 'systemMappings': []}}, 'action': {'actionType': 1, 'mainSql': 'select * from `student`', 'sortSql': '`id` desc', 'filterSql': '', 'mainSqlParams': None, 'filterSqlParams': [], 'assignment': {'ioAssignments': [{'displayName': 'name', 'relativeVariable': 'A12', 'dataType': 16384}, {'displayName': 'age', 'relativeVariable': 'A2', 'dataType': 2}, {'displayName': 'money', 'relativeVariable': 'A10', 'dataType': 512}], 'innerAssignments': [{'displayName': 'time', 'relativeVariable': 'aa16', 'dataType': 8192}], 'systemAssignments': None}}, 'status': 1, 'prevStatus': 0, 'lastErrorMsg': None, 'lastErrorDateTime': None}
[2023-12-19 14:06:54,067] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:06:54,067] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:06:55,079] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:55,079] logger_util.py->write_log line:61 [INFO] 接口名称：执行查询语句
[2023-12-19 14:06:55,079] logger_util.py->write_log line:61 [INFO] 接口方式：get
[2023-12-19 14:06:55,079] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/3/executetest
[2023-12-19 14:06:55,079] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:55,079] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:55,617] logger_util.py->error_log line:65 [INFO] 断言失败:A12不等于中文1
[2023-12-19 14:06:55,617] logger_util.py->write_log line:61 [INFO] 实际结果：{'record': {'dateTime': '2023/12/19 14:06:55', 'action': '查询', 'status': '成功', 'data': {'A12': '', 'A2': '', 'A10': '', 'aa16': ''}}, 'info': '测试时间: 2023/12/19 14:06:55\r\n动作: 查询\r\n\r\n数据库:\r\n执行结果: OK\r\n查询时间: 0.00s\r\n\r\n变量:\r\n下发结果: OK\r\n', 'status': 1, 'lastErrorMsg': None}
[2023-12-19 14:06:55,617] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-12-19 14:06:55,617] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-12-19 14:06:55,617] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 381, in validate_result
    error_log("断言失败:" + assert_key + "不等于" + str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:A12不等于中文1

[2023-12-19 14:06:55,618] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 381, in validate_result
    error_log("断言失败:" + assert_key + "不等于" + str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:A12不等于中文1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 248, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 381, in validate_result
    error_log("断言失败:" + assert_key + "不等于" + str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:A12不等于中文1


[2023-12-19 14:06:55,655] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:55,655] logger_util.py->write_log line:61 [INFO] 接口名称：刷新-查询
[2023-12-19 14:06:55,656] logger_util.py->write_log line:61 [INFO] 接口方式：get
[2023-12-19 14:06:55,656] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/3/preview
[2023-12-19 14:06:55,656] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:55,656] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:55,666] logger_util.py->error_log line:65 [INFO] 断言失败:age不等于10
[2023-12-19 14:06:55,666] logger_util.py->write_log line:61 [INFO] 实际结果：{'status': 1, 'lastErrorMsg': None, 'total': 1, 'headers': ['id', 'time', 'name', 'age', 'money'], 'data': [{'id': 1, 'time': None, 'name': None, 'age': None, 'money': None}]}
[2023-12-19 14:06:55,666] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-12-19 14:06:55,666] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-12-19 14:06:55,666] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 381, in validate_result
    error_log("断言失败:" + assert_key + "不等于" + str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:age不等于10

[2023-12-19 14:06:55,667] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 381, in validate_result
    error_log("断言失败:" + assert_key + "不等于" + str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:age不等于10

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 248, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 381, in validate_result
    error_log("断言失败:" + assert_key + "不等于" + str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:age不等于10


[2023-12-19 14:06:55,707] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:55,708] logger_util.py->write_log line:61 [INFO] 接口名称：下发A2=70
[2023-12-19 14:06:55,708] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-12-19 14:06:55,708] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/setvalues
[2023-12-19 14:06:55,708] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981', 'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiU3VwZXJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiU3VwZXJBZG1pbiIsImV4cCI6MTcwMjk0OTM5MiwiaXNzIjoiQ01TdjIiLCJhdWQiOiJBcGkifQ.DTE3ExRd5e35qx7qyEGhaNLjjzP8QxhHUoLCzYg7Hcc'}
[2023-12-19 14:06:55,708] logger_util.py->write_log line:61 [INFO] 请求参数：{'A2': '70'}
[2023-12-19 14:06:55,708] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:55,710] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-12-19 14:06:55,710] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-12-19 14:06:55,710] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-12-19 14:06:55,710] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-12-19 14:06:55,711] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-12-19 14:06:55,711] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 265, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-12-19 14:06:55,763] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:55,763] logger_util.py->write_log line:61 [INFO] 接口名称：下发A10=70.456
[2023-12-19 14:06:55,763] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-12-19 14:06:55,764] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/setvalues
[2023-12-19 14:06:55,764] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981', 'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiU3VwZXJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiU3VwZXJBZG1pbiIsImV4cCI6MTcwMjk0OTM5MiwiaXNzIjoiQ01TdjIiLCJhdWQiOiJBcGkifQ.DTE3ExRd5e35qx7qyEGhaNLjjzP8QxhHUoLCzYg7Hcc'}
[2023-12-19 14:06:55,764] logger_util.py->write_log line:61 [INFO] 请求参数：{'A10': '70.456'}
[2023-12-19 14:06:55,764] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:55,766] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-12-19 14:06:55,766] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-12-19 14:06:55,766] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-12-19 14:06:55,766] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-12-19 14:06:55,766] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-12-19 14:06:55,767] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 265, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-12-19 14:06:55,809] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:55,809] logger_util.py->write_log line:61 [INFO] 接口名称：下发A12=中文1
[2023-12-19 14:06:55,809] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-12-19 14:06:55,809] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/setvalues
[2023-12-19 14:06:55,809] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981', 'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiU3VwZXJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiU3VwZXJBZG1pbiIsImV4cCI6MTcwMjk0OTM5MiwiaXNzIjoiQ01TdjIiLCJhdWQiOiJBcGkifQ.DTE3ExRd5e35qx7qyEGhaNLjjzP8QxhHUoLCzYg7Hcc'}
[2023-12-19 14:06:55,809] logger_util.py->write_log line:61 [INFO] 请求参数：{'A12': '中文1'}
[2023-12-19 14:06:55,809] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:55,811] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-12-19 14:06:55,811] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-12-19 14:06:55,812] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-12-19 14:06:55,812] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-12-19 14:06:55,812] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-12-19 14:06:55,812] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 265, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-12-19 14:06:55,858] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:55,858] logger_util.py->write_log line:61 [INFO] 接口名称：下发aa16=2022-11-28 09:05:01
[2023-12-19 14:06:55,858] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-12-19 14:06:55,859] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/setvalues
[2023-12-19 14:06:55,859] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981', 'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiU3VwZXJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiU3VwZXJBZG1pbiIsImV4cCI6MTcwMjk0OTM5MiwiaXNzIjoiQ01TdjIiLCJhdWQiOiJBcGkifQ.DTE3ExRd5e35qx7qyEGhaNLjjzP8QxhHUoLCzYg7Hcc'}
[2023-12-19 14:06:55,859] logger_util.py->write_log line:61 [INFO] 请求参数：{'aa16': '2022-11-28 09:05:01'}
[2023-12-19 14:06:55,859] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:55,861] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-12-19 14:06:55,861] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-12-19 14:06:55,861] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-12-19 14:06:55,861] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-12-19 14:06:55,862] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-12-19 14:06:55,862] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 265, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-12-19 14:06:55,904] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:55,905] logger_util.py->write_log line:61 [INFO] 接口名称：创建映射表-修改
[2023-12-19 14:06:55,905] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-12-19 14:06:55,905] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/2/table
[2023-12-19 14:06:55,905] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:55,905] logger_util.py->write_log line:61 [INFO] 请求参数：{'isBasic': True, 'databaseTableName': 'student', 'querySql': '', 'name': 'student_修改6588'}
[2023-12-19 14:06:55,905] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:55,935] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:06:55,936] logger_util.py->write_log line:61 [INFO] 实际结果：{'id': 4, 'name': 'student_修改6588', 'connectionItemId': 2, 'fields': [{'tableName': 'student', 'tableAlias': '', 'columnName': 'id', 'displayName': 'id', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'time', 'displayName': 'time', 'dataTypeName': 'DateTime', 'databaseTypeName': 'DateTime', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'name', 'displayName': 'name', 'dataTypeName': 'String', 'databaseTypeName': 'VarChar', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'age', 'displayName': 'age', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'money', 'displayName': 'money', 'dataTypeName': 'Single', 'databaseTypeName': 'Float', 'isValueType': True, 'isAsterisk': True}], 'isBasic': True, 'basicDatabaseTableName': 'student', 'querySql': 'select * from `student`', 'detail': None, 'action': None, 'status': 1, 'prevStatus': 0, 'lastErrorMsg': None, 'lastErrorDateTime': None}
[2023-12-19 14:06:55,936] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:06:55,936] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:06:56,949] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:56,949] logger_util.py->write_log line:61 [INFO] 接口名称：保存配置-查询
[2023-12-19 14:06:56,949] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-12-19 14:06:56,949] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/4/save
[2023-12-19 14:06:56,950] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:56,950] logger_util.py->write_log line:61 [INFO] 请求参数：{'actionType': 3, 'filters': [[{'field': 'name', 'operatorType': 1, 'operand': 'A12', 'isVariable': True, 'isValueType': False}]], 'sorts': [{'field': 'id', 'sortType': 2}], 'mappings': [{'field': 'time', 'relativeVariable': 'aa16', 'dataType': '日期时间', 'order': 1}, {'field': 'name', 'relativeVariable': 'A12', 'dataType': '字符串', 'order': 2}, {'field': 'age', 'relativeVariable': 'A2', 'dataType': '有符号8位整型', 'order': 3}, {'field': 'money', 'relativeVariable': 'A10', 'dataType': 'F32位浮点数IEEE754', 'order': 4}]}
[2023-12-19 14:06:56,950] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:56,984] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:06:56,984] logger_util.py->write_log line:61 [INFO] 实际结果：{'id': 4, 'name': 'student_修改6588', 'connectionItemId': 2, 'fields': [{'tableName': 'student', 'tableAlias': '', 'columnName': 'id', 'displayName': 'id', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'time', 'displayName': 'time', 'dataTypeName': 'DateTime', 'databaseTypeName': 'DateTime', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'name', 'displayName': 'name', 'dataTypeName': 'String', 'databaseTypeName': 'VarChar', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'age', 'displayName': 'age', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'money', 'displayName': 'money', 'dataTypeName': 'Single', 'databaseTypeName': 'Float', 'isValueType': True, 'isAsterisk': True}], 'isBasic': True, 'basicDatabaseTableName': 'student', 'querySql': 'select * from `student`', 'detail': {'actionType': 3, 'filters': [[{'displayName': 'name', 'logicalOperatorType': 1, 'operand': 'A12', 'isVariable': True}]], 'sorts': [{'displayName': 'id', 'sortType': 2}], 'mapping': {'pendingDisplayNameRelativeVariable': None, 'ioMappings': [{'displayName': 'name', 'relativeVariable': 'A12', 'dataType': 16384, 'order': 2}, {'displayName': 'age', 'relativeVariable': 'A2', 'dataType': 2, 'order': 3}, {'displayName': 'money', 'relativeVariable': 'A10', 'dataType': 512, 'order': 4}], 'innerMappings': [{'displayName': 'time', 'relativeVariable': 'aa16', 'dataType': 8192, 'order': 1}], 'systemMappings': []}}, 'action': {'actionType': 3, 'mainSql': 'update `student` set `name`={0},`age`={1},`money`={2},`time`={3}', 'sortSql': '`id` desc', 'filterSql': '(`name` = {0})', 'mainSqlParams': [{'key': 'A12', 'value': False}, {'key': 'A2', 'value': True}, {'key': 'A10', 'value': True}, {'key': 'aa16', 'value': False}], 'filterSqlParams': [{'key': 'A12', 'value': False}], 'assignment': None}, 'status': 1, 'prevStatus': 0, 'lastErrorMsg': None, 'lastErrorDateTime': None}
[2023-12-19 14:06:56,984] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:06:56,984] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:06:58,004] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:58,004] logger_util.py->write_log line:61 [INFO] 接口名称：执行修改语句
[2023-12-19 14:06:58,004] logger_util.py->write_log line:61 [INFO] 接口方式：get
[2023-12-19 14:06:58,004] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/4/executetest
[2023-12-19 14:06:58,004] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:58,004] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:58,527] logger_util.py->error_log line:65 [INFO] 断言失败:A12不等于中文1
[2023-12-19 14:06:58,527] logger_util.py->write_log line:61 [INFO] 实际结果：{'record': {'dateTime': '2023/12/19 14:06:58', 'action': '修改', 'status': '成功', 'data': {'A12': '', 'A2': '', 'A10': '', 'aa16': ''}}, 'info': '测试时间: 2023/12/19 14:06:58\r\n动作: 修改\r\n\r\n数据库:\r\n执行结果: OK\r\n写入时间: 0.00s\r\n', 'status': 1, 'lastErrorMsg': None}
[2023-12-19 14:06:58,527] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-12-19 14:06:58,527] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-12-19 14:06:58,527] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 381, in validate_result
    error_log("断言失败:" + assert_key + "不等于" + str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:A12不等于中文1

[2023-12-19 14:06:58,528] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 381, in validate_result
    error_log("断言失败:" + assert_key + "不等于" + str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:A12不等于中文1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 248, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 381, in validate_result
    error_log("断言失败:" + assert_key + "不等于" + str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:A12不等于中文1


[2023-12-19 14:06:58,567] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:58,567] logger_util.py->write_log line:61 [INFO] 接口名称：刷新-修改
[2023-12-19 14:06:58,567] logger_util.py->write_log line:61 [INFO] 接口方式：get
[2023-12-19 14:06:58,567] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/4/preview
[2023-12-19 14:06:58,567] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:58,567] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:58,577] logger_util.py->error_log line:65 [INFO] 断言失败：返回结果中不存在：age
[2023-12-19 14:06:58,577] logger_util.py->write_log line:61 [INFO] 实际结果：{'status': 1, 'lastErrorMsg': None, 'total': 0, 'headers': ['id', 'time', 'name', 'age', 'money'], 'data': []}
[2023-12-19 14:06:58,578] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-12-19 14:06:58,578] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-12-19 14:06:58,578] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 384, in validate_result
    error_log("断言失败：返回结果中不存在："+assert_key)
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败：返回结果中不存在：age

[2023-12-19 14:06:58,578] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 384, in validate_result
    error_log("断言失败：返回结果中不存在："+assert_key)
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败：返回结果中不存在：age

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 248, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 384, in validate_result
    error_log("断言失败：返回结果中不存在："+assert_key)
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败：返回结果中不存在：age


[2023-12-19 14:06:58,702] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:58,703] logger_util.py->write_log line:61 [INFO] 接口名称：下发A2=77
[2023-12-19 14:06:58,703] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-12-19 14:06:58,703] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/setvalues
[2023-12-19 14:06:58,703] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981', 'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiU3VwZXJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiU3VwZXJBZG1pbiIsImV4cCI6MTcwMjk0OTM5MiwiaXNzIjoiQ01TdjIiLCJhdWQiOiJBcGkifQ.DTE3ExRd5e35qx7qyEGhaNLjjzP8QxhHUoLCzYg7Hcc'}
[2023-12-19 14:06:58,703] logger_util.py->write_log line:61 [INFO] 请求参数：{'A2': '77'}
[2023-12-19 14:06:58,703] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:58,705] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-12-19 14:06:58,705] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-12-19 14:06:58,705] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-12-19 14:06:58,706] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-12-19 14:06:58,706] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-12-19 14:06:58,706] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 265, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-12-19 14:06:58,820] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:58,820] logger_util.py->write_log line:61 [INFO] 接口名称：下发A10=77.456
[2023-12-19 14:06:58,820] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-12-19 14:06:58,820] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/setvalues
[2023-12-19 14:06:58,820] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981', 'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiU3VwZXJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiU3VwZXJBZG1pbiIsImV4cCI6MTcwMjk0OTM5MiwiaXNzIjoiQ01TdjIiLCJhdWQiOiJBcGkifQ.DTE3ExRd5e35qx7qyEGhaNLjjzP8QxhHUoLCzYg7Hcc'}
[2023-12-19 14:06:58,820] logger_util.py->write_log line:61 [INFO] 请求参数：{'A10': '77.456'}
[2023-12-19 14:06:58,821] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:58,823] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-12-19 14:06:58,823] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-12-19 14:06:58,823] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-12-19 14:06:58,823] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-12-19 14:06:58,824] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-12-19 14:06:58,824] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 265, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-12-19 14:06:58,953] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:58,953] logger_util.py->write_log line:61 [INFO] 接口名称：下发A12=中文1
[2023-12-19 14:06:58,953] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-12-19 14:06:58,953] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/setvalues
[2023-12-19 14:06:58,953] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981', 'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiU3VwZXJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiU3VwZXJBZG1pbiIsImV4cCI6MTcwMjk0OTM5MiwiaXNzIjoiQ01TdjIiLCJhdWQiOiJBcGkifQ.DTE3ExRd5e35qx7qyEGhaNLjjzP8QxhHUoLCzYg7Hcc'}
[2023-12-19 14:06:58,953] logger_util.py->write_log line:61 [INFO] 请求参数：{'A12': '中文1'}
[2023-12-19 14:06:58,953] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:58,956] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-12-19 14:06:58,956] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-12-19 14:06:58,956] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-12-19 14:06:58,956] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-12-19 14:06:58,956] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-12-19 14:06:58,957] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 265, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-12-19 14:06:59,077] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:59,078] logger_util.py->write_log line:61 [INFO] 接口名称：下发aa16=2022-11-28 09:05:01
[2023-12-19 14:06:59,078] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-12-19 14:06:59,078] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/setvalues
[2023-12-19 14:06:59,078] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981', 'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiU3VwZXJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiU3VwZXJBZG1pbiIsImV4cCI6MTcwMjk0OTM5MiwiaXNzIjoiQ01TdjIiLCJhdWQiOiJBcGkifQ.DTE3ExRd5e35qx7qyEGhaNLjjzP8QxhHUoLCzYg7Hcc'}
[2023-12-19 14:06:59,078] logger_util.py->write_log line:61 [INFO] 请求参数：{'aa16': '2022-11-28 09:05:01'}
[2023-12-19 14:06:59,078] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:59,080] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-12-19 14:06:59,080] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-12-19 14:06:59,081] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-12-19 14:06:59,081] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-12-19 14:06:59,081] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-12-19 14:06:59,081] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 265, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-12-19 14:06:59,132] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:06:59,132] logger_util.py->write_log line:61 [INFO] 接口名称：创建映射表-定时触发-插入
[2023-12-19 14:06:59,132] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-12-19 14:06:59,132] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/2/table
[2023-12-19 14:06:59,132] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:06:59,132] logger_util.py->write_log line:61 [INFO] 请求参数：{'isBasic': True, 'databaseTableName': 'student', 'querySql': '', 'name': '定时_插入4630'}
[2023-12-19 14:06:59,133] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:06:59,158] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:06:59,158] logger_util.py->write_log line:61 [INFO] 实际结果：{'id': 5, 'name': '定时_插入4630', 'connectionItemId': 2, 'fields': [{'tableName': 'student', 'tableAlias': '', 'columnName': 'id', 'displayName': 'id', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'time', 'displayName': 'time', 'dataTypeName': 'DateTime', 'databaseTypeName': 'DateTime', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'name', 'displayName': 'name', 'dataTypeName': 'String', 'databaseTypeName': 'VarChar', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'age', 'displayName': 'age', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'money', 'displayName': 'money', 'dataTypeName': 'Single', 'databaseTypeName': 'Float', 'isValueType': True, 'isAsterisk': True}], 'isBasic': True, 'basicDatabaseTableName': 'student', 'querySql': 'select * from `student`', 'detail': None, 'action': None, 'status': 1, 'prevStatus': 0, 'lastErrorMsg': None, 'lastErrorDateTime': None}
[2023-12-19 14:06:59,158] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:06:59,158] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:07:00,177] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:07:00,177] logger_util.py->write_log line:61 [INFO] 接口名称：保存配置-插入
[2023-12-19 14:07:00,177] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-12-19 14:07:00,177] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/5/save
[2023-12-19 14:07:00,177] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:07:00,178] logger_util.py->write_log line:61 [INFO] 请求参数：{'actionType': 2, 'filters': [], 'sorts': [{'field': 'id', 'sortType': 2}], 'mappings': [{'field': 'time', 'relativeVariable': 'aa16', 'dataType': '日期时间', 'order': 1}, {'field': 'name', 'relativeVariable': 'A12', 'dataType': '字符串', 'order': 2}, {'field': 'age', 'relativeVariable': 'A2', 'dataType': '有符号8位整型', 'order': 3}, {'field': 'money', 'relativeVariable': 'A10', 'dataType': 'F32位浮点数IEEE754', 'order': 4}]}
[2023-12-19 14:07:00,178] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:07:00,206] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:07:00,206] logger_util.py->write_log line:61 [INFO] 实际结果：{'id': 5, 'name': '定时_插入4630', 'connectionItemId': 2, 'fields': [{'tableName': 'student', 'tableAlias': '', 'columnName': 'id', 'displayName': 'id', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'time', 'displayName': 'time', 'dataTypeName': 'DateTime', 'databaseTypeName': 'DateTime', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'name', 'displayName': 'name', 'dataTypeName': 'String', 'databaseTypeName': 'VarChar', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'age', 'displayName': 'age', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'money', 'displayName': 'money', 'dataTypeName': 'Single', 'databaseTypeName': 'Float', 'isValueType': True, 'isAsterisk': True}], 'isBasic': True, 'basicDatabaseTableName': 'student', 'querySql': 'select * from `student`', 'detail': {'actionType': 2, 'filters': [], 'sorts': [{'displayName': 'id', 'sortType': 2}], 'mapping': {'pendingDisplayNameRelativeVariable': None, 'ioMappings': [{'displayName': 'name', 'relativeVariable': 'A12', 'dataType': 16384, 'order': 2}, {'displayName': 'age', 'relativeVariable': 'A2', 'dataType': 2, 'order': 3}, {'displayName': 'money', 'relativeVariable': 'A10', 'dataType': 512, 'order': 4}], 'innerMappings': [{'displayName': 'time', 'relativeVariable': 'aa16', 'dataType': 8192, 'order': 1}], 'systemMappings': []}}, 'action': {'actionType': 2, 'mainSql': 'insert into `student` (`name`,`age`,`money`,`time`) values ({0},{1},{2},{3})', 'sortSql': '`id` desc', 'filterSql': '', 'mainSqlParams': [{'key': 'A12', 'value': False}, {'key': 'A2', 'value': True}, {'key': 'A10', 'value': True}, {'key': 'aa16', 'value': False}], 'filterSqlParams': [], 'assignment': None}, 'status': 1, 'prevStatus': 0, 'lastErrorMsg': None, 'lastErrorDateTime': None}
[2023-12-19 14:07:00,206] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:07:00,207] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:07:01,229] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:07:01,229] logger_util.py->write_log line:61 [INFO] 接口名称：触发配置-定时
[2023-12-19 14:07:01,229] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-12-19 14:07:01,229] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/5/trigger/save
[2023-12-19 14:07:01,230] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:07:01,230] logger_util.py->write_log line:61 [INFO] 请求参数：[{'effectiveDateTime': '2023-11-28T06:55:22.000Z', 'frequencyValue': 1, 'frequencyUnit': 1, 'matchAll': True, 'condition': 'A2>10', 'conditionDetail': 1, 'frequencyCheck': False, 'alarmPointIds': [], 'triggerType': 1}]
[2023-12-19 14:07:01,230] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:07:01,333] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:07:01,334] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-12-19 14:07:01,334] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:07:01,334] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:07:02,355] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:07:02,355] logger_util.py->write_log line:61 [INFO] 接口名称：刷新-定时触发-插入
[2023-12-19 14:07:02,355] logger_util.py->write_log line:61 [INFO] 接口方式：get
[2023-12-19 14:07:02,355] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/5/preview
[2023-12-19 14:07:02,355] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:07:02,355] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:07:02,364] logger_util.py->error_log line:65 [INFO] 断言失败：返回结果中不存在：age
[2023-12-19 14:07:02,364] logger_util.py->write_log line:61 [INFO] 实际结果：{'status': 1, 'lastErrorMsg': None, 'total': 0, 'headers': ['id', 'time', 'name', 'age', 'money'], 'data': []}
[2023-12-19 14:07:02,364] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-12-19 14:07:02,364] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-12-19 14:07:02,365] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 384, in validate_result
    error_log("断言失败：返回结果中不存在："+assert_key)
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败：返回结果中不存在：age

[2023-12-19 14:07:02,365] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 384, in validate_result
    error_log("断言失败：返回结果中不存在："+assert_key)
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败：返回结果中不存在：age

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 248, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 384, in validate_result
    error_log("断言失败：返回结果中不存在："+assert_key)
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败：返回结果中不存在：age


[2023-12-19 14:07:02,497] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:07:02,497] logger_util.py->write_log line:61 [INFO] 接口名称：禁用定时插入映射表
[2023-12-19 14:07:02,497] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-12-19 14:07:02,497] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/switch/2/5/off
[2023-12-19 14:07:02,497] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:07:02,498] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:07:02,518] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:07:02,518] logger_util.py->write_log line:61 [INFO] 实际结果：[{'nodeGuid': '78e75a40-e9ec-47e8-b2bc-553fa0be416b', 'id': 5, 'type': 2, 'name': '定时_插入4630', 'status': 2, 'errorMsg': None, 'children': []}]
[2023-12-19 14:07:02,518] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:07:02,518] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:07:02,526] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:07:02,526] logger_util.py->write_log line:61 [INFO] 接口名称：创建映射表-变量触发-插入
[2023-12-19 14:07:02,526] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-12-19 14:07:02,527] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/2/table
[2023-12-19 14:07:02,527] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:07:02,527] logger_util.py->write_log line:61 [INFO] 请求参数：{'isBasic': True, 'databaseTableName': 'student', 'querySql': '', 'name': '变量_插入1655'}
[2023-12-19 14:07:02,527] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:07:02,554] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:07:02,554] logger_util.py->write_log line:61 [INFO] 实际结果：{'id': 6, 'name': '变量_插入1655', 'connectionItemId': 2, 'fields': [{'tableName': 'student', 'tableAlias': '', 'columnName': 'id', 'displayName': 'id', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'time', 'displayName': 'time', 'dataTypeName': 'DateTime', 'databaseTypeName': 'DateTime', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'name', 'displayName': 'name', 'dataTypeName': 'String', 'databaseTypeName': 'VarChar', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'age', 'displayName': 'age', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'money', 'displayName': 'money', 'dataTypeName': 'Single', 'databaseTypeName': 'Float', 'isValueType': True, 'isAsterisk': True}], 'isBasic': True, 'basicDatabaseTableName': 'student', 'querySql': 'select * from `student`', 'detail': None, 'action': None, 'status': 1, 'prevStatus': 0, 'lastErrorMsg': None, 'lastErrorDateTime': None}
[2023-12-19 14:07:02,554] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:07:02,554] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:07:04,574] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:07:04,574] logger_util.py->write_log line:61 [INFO] 接口名称：保存配置-插入
[2023-12-19 14:07:04,574] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-12-19 14:07:04,574] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/6/save
[2023-12-19 14:07:04,574] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:07:04,575] logger_util.py->write_log line:61 [INFO] 请求参数：{'actionType': 2, 'filters': [], 'sorts': [{'field': 'id', 'sortType': 2}], 'mappings': [{'field': 'time', 'relativeVariable': 'aa16', 'dataType': '日期时间', 'order': 1}, {'field': 'name', 'relativeVariable': 'A12', 'dataType': '字符串', 'order': 2}, {'field': 'age', 'relativeVariable': 'A2', 'dataType': '有符号8位整型', 'order': 3}, {'field': 'money', 'relativeVariable': 'A10', 'dataType': 'F32位浮点数IEEE754', 'order': 4}]}
[2023-12-19 14:07:04,575] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:07:04,603] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:07:04,603] logger_util.py->write_log line:61 [INFO] 实际结果：{'id': 6, 'name': '变量_插入1655', 'connectionItemId': 2, 'fields': [{'tableName': 'student', 'tableAlias': '', 'columnName': 'id', 'displayName': 'id', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'time', 'displayName': 'time', 'dataTypeName': 'DateTime', 'databaseTypeName': 'DateTime', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'name', 'displayName': 'name', 'dataTypeName': 'String', 'databaseTypeName': 'VarChar', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'age', 'displayName': 'age', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'money', 'displayName': 'money', 'dataTypeName': 'Single', 'databaseTypeName': 'Float', 'isValueType': True, 'isAsterisk': True}], 'isBasic': True, 'basicDatabaseTableName': 'student', 'querySql': 'select * from `student`', 'detail': {'actionType': 2, 'filters': [], 'sorts': [{'displayName': 'id', 'sortType': 2}], 'mapping': {'pendingDisplayNameRelativeVariable': None, 'ioMappings': [{'displayName': 'name', 'relativeVariable': 'A12', 'dataType': 16384, 'order': 2}, {'displayName': 'age', 'relativeVariable': 'A2', 'dataType': 2, 'order': 3}, {'displayName': 'money', 'relativeVariable': 'A10', 'dataType': 512, 'order': 4}], 'innerMappings': [{'displayName': 'time', 'relativeVariable': 'aa16', 'dataType': 8192, 'order': 1}], 'systemMappings': []}}, 'action': {'actionType': 2, 'mainSql': 'insert into `student` (`name`,`age`,`money`,`time`) values ({0},{1},{2},{3})', 'sortSql': '`id` desc', 'filterSql': '', 'mainSqlParams': [{'key': 'A12', 'value': False}, {'key': 'A2', 'value': True}, {'key': 'A10', 'value': True}, {'key': 'aa16', 'value': False}], 'filterSqlParams': [], 'assignment': None}, 'status': 1, 'prevStatus': 0, 'lastErrorMsg': None, 'lastErrorDateTime': None}
[2023-12-19 14:07:04,603] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:07:04,603] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:07:06,620] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:07:06,620] logger_util.py->write_log line:61 [INFO] 接口名称：触发配置-变量触发
[2023-12-19 14:07:06,620] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-12-19 14:07:06,620] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/6/trigger/save
[2023-12-19 14:07:06,620] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:07:06,620] logger_util.py->write_log line:61 [INFO] 请求参数：[{'effectiveDateTime': '', 'frequencyValue': 1, 'frequencyUnit': 1, 'matchAll': False, 'condition': 'A1', 'conditionDetail': 1, 'frequencyCheck': False, 'alarmPointIds': [], 'triggerType': 2}]
[2023-12-19 14:07:06,620] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:07:06,644] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:07:06,645] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-12-19 14:07:06,645] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:07:06,645] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-12-19 14:07:08,658] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:07:08,658] logger_util.py->write_log line:61 [INFO] 接口名称：下发A1=false
[2023-12-19 14:07:08,658] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-12-19 14:07:08,658] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/setvalues
[2023-12-19 14:07:08,658] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981', 'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiU3VwZXJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiU3VwZXJBZG1pbiIsImV4cCI6MTcwMjk0OTM5MiwiaXNzIjoiQ01TdjIiLCJhdWQiOiJBcGkifQ.DTE3ExRd5e35qx7qyEGhaNLjjzP8QxhHUoLCzYg7Hcc'}
[2023-12-19 14:07:08,659] logger_util.py->write_log line:61 [INFO] 请求参数：{'A1': 'false'}
[2023-12-19 14:07:08,659] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:07:08,661] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-12-19 14:07:08,661] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-12-19 14:07:08,661] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-12-19 14:07:08,661] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-12-19 14:07:08,661] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-12-19 14:07:08,662] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 265, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-12-19 14:07:08,704] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:07:08,705] logger_util.py->write_log line:61 [INFO] 接口名称：下发A1=true
[2023-12-19 14:07:08,705] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-12-19 14:07:08,705] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/setvalues
[2023-12-19 14:07:08,705] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981', 'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiU3VwZXJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiU3VwZXJBZG1pbiIsImV4cCI6MTcwMjk0OTM5MiwiaXNzIjoiQ01TdjIiLCJhdWQiOiJBcGkifQ.DTE3ExRd5e35qx7qyEGhaNLjjzP8QxhHUoLCzYg7Hcc'}
[2023-12-19 14:07:08,705] logger_util.py->write_log line:61 [INFO] 请求参数：{'A1': 'true'}
[2023-12-19 14:07:08,705] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:07:08,707] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-12-19 14:07:08,708] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-12-19 14:07:08,708] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-12-19 14:07:08,708] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-12-19 14:07:08,708] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-12-19 14:07:08,708] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 265, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-12-19 14:07:08,748] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:07:08,748] logger_util.py->write_log line:61 [INFO] 接口名称：刷新-变量触发-插入
[2023-12-19 14:07:08,748] logger_util.py->write_log line:61 [INFO] 接口方式：get
[2023-12-19 14:07:08,748] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/6/preview
[2023-12-19 14:07:08,749] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:07:08,749] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:07:08,758] logger_util.py->error_log line:65 [INFO] 断言失败：返回结果中不存在：age
[2023-12-19 14:07:08,758] logger_util.py->write_log line:61 [INFO] 实际结果：{'status': 1, 'lastErrorMsg': None, 'total': 0, 'headers': ['id', 'time', 'name', 'age', 'money'], 'data': []}
[2023-12-19 14:07:08,758] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-12-19 14:07:08,758] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-12-19 14:07:08,758] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 384, in validate_result
    error_log("断言失败：返回结果中不存在："+assert_key)
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败：返回结果中不存在：age

[2023-12-19 14:07:08,759] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 384, in validate_result
    error_log("断言失败：返回结果中不存在："+assert_key)
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败：返回结果中不存在：age

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 248, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 384, in validate_result
    error_log("断言失败：返回结果中不存在："+assert_key)
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败：返回结果中不存在：age


[2023-12-19 14:07:08,886] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-12-19 14:07:08,886] logger_util.py->write_log line:61 [INFO] 接口名称：禁用变量插入映射表
[2023-12-19 14:07:08,886] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-12-19 14:07:08,886] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/switch/2/6/off
[2023-12-19 14:07:08,886] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-12-19 14:07:08,886] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-12-19 14:07:08,909] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-12-19 14:07:08,909] logger_util.py->write_log line:61 [INFO] 实际结果：[{'nodeGuid': '4acecf17-2bd0-4c17-91d5-141e7d208342', 'id': 6, 'type': 2, 'name': '变量_插入1655', 'status': 2, 'errorMsg': None, 'children': []}]
[2023-12-19 14:07:08,909] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-12-19 14:07:08,909] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

