[2022-10-10 11:26:45,949] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 198, in analysis_yaml
    files[key] = open(value,'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Project_python\\2TestCMS2.0\\testcase\\4.8m.jpg'

