[2022-12-02 14:29:51,438] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:51,439] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:51,591] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:51,591] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:51,624] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:51,624] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:51,656] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:51,656] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:51,688] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:51,689] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:51,719] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:51,719] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:51,750] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:51,751] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:51,781] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:51,782] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:51,813] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:51,813] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:51,845] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:51,845] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:51,877] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:51,878] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:51,909] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:51,909] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:51,942] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:51,942] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:51,973] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:51,973] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,005] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,005] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,037] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,038] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,070] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,071] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,104] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,105] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,138] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,139] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,185] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,185] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,217] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,218] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,249] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,250] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,282] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,282] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,315] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,316] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,349] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,349] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,381] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,382] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,414] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,415] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,446] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,446] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,478] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,479] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,511] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,512] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,543] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,544] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,579] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,580] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,611] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,612] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,644] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,644] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,674] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,676] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,709] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,709] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,742] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,742] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,774] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,774] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,819] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,820] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,851] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,851] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,882] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,883] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,913] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,914] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,946] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,946] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:52,978] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:52,979] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:53,010] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:53,011] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:53,043] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:53,043] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:53,073] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:53,074] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2022-12-02 14:29:53,105] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2022-12-02 14:29:53,105] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 204, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 360, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 332, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 46, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\2TestCMS2.0\debug_talk.py", line 16, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\2TestCMS2.0\common\yaml_util.py", line 20, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


