[2023-08-17 15:08:26,926] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2023-08-17 15:08:26,927] logger_util.py->write_log line:61 [INFO] 接口名称：检查本地工程id是否冲突
[2023-08-17 15:08:26,927] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-17 15:08:26,927] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/project/node/checklocalprojectfileidconflict
[2023-08-17 15:08:26,927] logger_util.py->write_log line:61 [INFO] 请求头：{}
[2023-08-17 15:08:26,927] logger_util.py->write_log line:61 [INFO] 请求参数：{'localFilePath': 'E:\\Project_python\\api_cms\\data\\EngineeringManagement\\rc9回归组件.cmsproj'}
[2023-08-17 15:08:26,927] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-17 15:08:26,942] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}, {'equals': {'result': False}}]
[2023-08-17 15:08:26,942] logger_util.py->write_log line:61 [INFO] 实际结果：{'result': False, 'conflictProjectID': -1}
[2023-08-17 15:08:26,942] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-08-17 15:08:26,942] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-17 15:08:26,947] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2023-08-17 15:08:26,947] logger_util.py->write_log line:61 [INFO] 接口名称：导入本地工程文件
[2023-08-17 15:08:26,947] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-17 15:08:26,947] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/project/node/importlocalproject
[2023-08-17 15:08:26,947] logger_util.py->write_log line:61 [INFO] 请求头：{}
[2023-08-17 15:08:26,947] logger_util.py->write_log line:61 [INFO] 请求参数：{'localFilePath': 'E:\\Project_python\\api_cms\\data\\EngineeringManagement\\rc9回归组件.cmsproj', 'importConflictHandleType': 1}
[2023-08-17 15:08:26,947] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-17 15:08:27,056] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-08-17 15:08:27,057] logger_util.py->write_log line:61 [INFO] 实际结果：{'id': 307, 'parentId': None, 'name': 'rc9回归组件', 'path': 'E:\\Project_python\\api_cms\\data\\EngineeringManagement\\rc9回归组件.cmsproj', 'type': 1, 'createTime': '2023-08-17T15:08:26.9512074+08:00', 'updateTime': '2023-08-17T15:08:26.9512076+08:00'}
[2023-08-17 15:08:27,058] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-08-17 15:08:27,058] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-17 15:08:27,067] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2023-08-17 15:08:27,067] logger_util.py->write_log line:61 [INFO] 接口名称：删除工程
[2023-08-17 15:08:27,067] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-08-17 15:08:27,067] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/project/node/deletenodes
[2023-08-17 15:08:27,067] logger_util.py->write_log line:61 [INFO] 请求头：{}
[2023-08-17 15:08:27,067] logger_util.py->write_log line:61 [INFO] 请求参数：{'ids': '307', 'isDeleteFile': False}
[2023-08-17 15:08:27,067] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-17 15:08:27,215] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-08-17 15:08:27,216] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-08-17 15:08:27,216] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-08-17 15:08:27,216] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-17 15:08:27,220] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2023-08-17 15:08:27,220] logger_util.py->write_log line:61 [INFO] 接口名称：检查远程工程id是否冲突
[2023-08-17 15:08:27,220] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-17 15:08:27,220] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/project/node/checkremoteprojectfileidconflict
[2023-08-17 15:08:27,220] logger_util.py->write_log line:61 [INFO] 请求头：{}
[2023-08-17 15:08:27,221] logger_util.py->write_log line:61 [INFO] 请求参数：{'localFilePath': 'E:\\Project_python\\api_cms\\data\\EngineeringManagement\\rc9回归组件.cmsproj'}
[2023-08-17 15:08:27,221] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-17 15:08:27,223] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-17 15:08:27,223] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-17 15:08:27,223] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-17 15:08:27,224] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-17 15:08:27,224] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-17 15:08:27,327] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2023-08-17 15:08:27,327] logger_util.py->write_log line:61 [INFO] 接口名称：导入远程工程文件
[2023-08-17 15:08:27,327] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-17 15:08:27,327] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/project/node/importremoteproject
[2023-08-17 15:08:27,327] logger_util.py->write_log line:61 [INFO] 请求头：{}
[2023-08-17 15:08:27,328] logger_util.py->write_log line:61 [INFO] 请求参数：{'localFilePath': 'E:\\Project_python\\api_cms\\data\\EngineeringManagement\\rc9回归组件.cmsproj', 'importConflictHandleType': 1}
[2023-08-17 15:08:27,328] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-17 15:08:27,330] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-17 15:08:27,330] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-17 15:08:27,330] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-17 15:08:27,331] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-17 15:08:27,331] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-17 15:08:27,359] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2023-08-17 15:08:27,359] logger_util.py->write_log line:61 [INFO] 接口名称：删除工程
[2023-08-17 15:08:27,359] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-08-17 15:08:27,359] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/project/node/deletenodes
[2023-08-17 15:08:27,359] logger_util.py->write_log line:61 [INFO] 请求头：{}
[2023-08-17 15:08:27,359] logger_util.py->write_log line:61 [INFO] 请求参数：{'ids': '307', 'isDeleteFile': False}
[2023-08-17 15:08:27,359] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-17 15:08:27,363] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-08-17 15:08:27,363] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-08-17 15:08:27,363] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-08-17 15:08:27,363] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

